/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import com.morethansimplycode.data.Data;
import com.morethansimplycode.crud.DataTableModel;
import com.morethansimplycode.management.DataListener;
import com.morethansimplycode.management.DataManagement;
import com.morethansimplycode.management.DataProcessor;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author Oscar
 */
public class Prueba extends javax.swing.JFrame implements DataListener {

    /**
     * Creates new form Prueba
     */
    public Prueba() {
        try {
            initComponents();

//        SingletonDataManagement.getInstance().setDataManagment(
//                new DataManagement("com.mysql.jdbc.Driver",
//                        "jdbc:mysql://192.168.1.46:3306/test", "test", "p@ssw0rd"));
            DataManagement conexion = new DataManagement("com.mysql.jdbc.Driver",
                    "jdbc:mysql://192.168.1.46:3306/test", "test", "p@ssw0rd");
            conexion.close();

            ArrayList<Data> ds = conexion.recoverData(Empleado1.class);
            tabla.setModel(new DataTableModel(Empleado1.class, ds));
            tabDetail.setClassData(Empleado1.class);
            tabDetail.setData(ds);

            /* Ejemplo de Aync */
//        SingletonDataManagement.getInstance().addDataListener(this);
//        SingletonDataManagement.getInstance().recoveryDataAsync(Empleado1.class);
            /* Ejemplo búsqueda */
//        DataSearch s = new DataSearch(Empleado.class);
//        s.addAndSearch("NOMBRE", "pepe");
//        s.addOrSearch("NOMBRE", "paco");
//        s.addOrSQL("NOMBRE = 'paco'");
//        ArrayList<Data> ds = SingletonDataManagement.getInstance().searchData(s);
            /* Ejemplo sin Async */
//        ArrayList<Data> ds = SingletonDataManagement.getInstance().recoverData(Empleado1.class);
            // Añadir un modelo
//        tabla.setModel(new DataTableModel(Empleado.class, ds));
//        tabDetail.setClassData(Empleado.class);
//        tabDetail.setData(ds);
            // Añadir un Listener para mostrar los datos seleccionados en la tabla
            // al DataTabDetail
            tabla.addCRUDTableListener((int newSelectedRow, int newSelectedColumn) -> {
                tabDetail.setSelectedData(tabla.getCRUDTableModel().getData()[newSelectedRow]);
            });
        } catch (Exception ex) {
            Logger.getLogger(Prueba.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabDetail = new com.morethansimplycode.crud.DataTabDetail();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new com.morethansimplycode.crud.CRUDTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Prueba().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.morethansimplycode.crud.DataTabDetail tabDetail;
    private com.morethansimplycode.crud.CRUDTable tabla;
    // End of variables declaration//GEN-END:variables

    /* The listening implementing zone */
    private final Class clase = Empleado.class;
    private final Class clase1 = Empleado1.class;

    @Override
    public Class<? extends Data> getClassforHandle() {

        return clase;
    }

    @Override
    public boolean isListeningClass(Class<? extends Data> dataClass) {

        return clase.equals(dataClass) || clase1.equals(dataClass);
    }

    @Override
    public void handleDataRecoveryNotCached(ArrayList<Data> data, DataProcessor processor) {

        SwingUtilities.invokeLater(() -> {

            tabla.setModel(new DataTableModel(Empleado1.class, data));

            // Set the data class for the detail
            tabDetail.setClassData(Empleado1.class);
            // The Data collection to show on the Tab
            tabDetail.setData(data);
        });
    }

    @Override
    public void handleDataRecoveryCached(String key, DataProcessor processor) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
