/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.morethansimplycode.crud;

import com.morethansimplycode.data.Data;
import java.util.List;

/**
 *
 * @author Oscar
 * Date 24-may-2015
 * Time 13:10:25
 */
public class DataTabDetail extends javax.swing.JPanel implements DataTabListener{

    
    
    /** Creates new form DataTabDetail */
    public DataTabDetail() {
        initComponents();
        tab.setListener(this);
    }

    public void setClassData(Class<? extends Data> d){
        
        detail.setClassData(d);
    }
    
    public void setData(Data[] data){
        
        tab.setData(data);
    }

    public void setSelectedData(Data data) {
        // TODO tab.setSelectedData();
        detail.setData(data);
    }

    public void setItemSize(int width, int height) {
        tab.setItemSize(width, height);
    }   
    
    public void setData(List<Data> data){
        
        tab.setData(data);
    }

    public Data getData() {
        return detail.getData();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new com.morethansimplycode.crud.DataTab();
        detail = new com.morethansimplycode.crud.DataDetail();

        detail.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
            .addComponent(detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detail, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.morethansimplycode.crud.DataDetail detail;
    private com.morethansimplycode.crud.DataTab tab;
    // End of variables declaration//GEN-END:variables

    @Override
    public void selectionChanged(Data newSelection) {
        
        detail.setData(newSelection);
    }

}
