/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.morethansimplycode.crud;

import com.morethansimplycode.data.Data;
import java.awt.Dimension;

/**
 *
 * @author Oscar
 * Date 21-may-2015
 * Time 22:26:21
 */
public class DataTabItem extends javax.swing.JPanel {

    Data value;
    
    /** Creates new form DataTabItem */
    public DataTabItem() {
        
        initComponents();
    }
    
    public DataTabItem(Data d, int height, int width) {
        
        initComponents();
        value = d;
        button.setPreferredSize(new Dimension(width, height));
        this.setPreferredSize(new Dimension(width, height));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        button.setBackground(new java.awt.Color(102, 102, 255));
        button.setText("PACO");
        button.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        add(button, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        System.out.println("hola");
    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    // End of variables declaration//GEN-END:variables

}
